In [4]:
import numpy as np
n=int(input("n: "))
matrix= np.random.rand(n,n)
print(matrix)

sum=0
for i in range(n):
    for j in range(n):
        sum+=(matrix[i][j]*matrix[i][j])
norm = np.sqrt(sum)
print("Norm: ",norm)

sum2=0
for x in range(n):
    sum2+=matrix[i][i]
print("Trace: ", sum2)


n: 4
[[0.37962652 0.08978669 0.10623179 0.56057901]
 [0.63083573 0.61789111 0.22272682 0.04800246]
 [0.57933491 0.68902958 0.35558687 0.29086927]
 [0.86199719 0.40022548 0.40726713 0.52241672]]
Norm:  1.9164575574687015
Trace:  2.0896668808174415
